<?xml version="1.0" encoding="UTF-8"?>
<ActionCollection version="2" name="Scripts">
    <Actions category="Scripts">
        <text>AI Tools: Image Generation</text>

        <Action name="ai_diffusion_generate">
            <icon />
            <text>Generate image</text>
            <whatsThis />
            <toolTip />
            <iconText />
            <activationFlags>10000</activationFlags>
            <activationConditions>0</activationConditions>
            <shortcut></shortcut>
            <isCheckable>false</isCheckable>
            <statusTip />
        </Action>
        <Action name="ai_diffusion_cancel">
            <icon />
            <text>Cancel current job</text>
            <whatsThis />
            <toolTip />
            <iconText />
            <activationFlags>10000</activationFlags>
            <activationConditions>0</activationConditions>
            <shortcut></shortcut>
            <isCheckable>false</isCheckable>
            <statusTip />
        </Action>
        <Action name="ai_diffusion_cancel_queued">
            <icon />
            <text>Cancel queued jobs</text>
            <whatsThis />
            <toolTip />
            <iconText />
            <activationFlags>10000</activationFlags>
            <activationConditions>0</activationConditions>
            <shortcut></shortcut>
            <isCheckable>false</isCheckable>
            <statusTip />
        </Action>
        <Action name="ai_diffusion_cancel_all">
            <icon />
            <text>Cancel all jobs</text>
            <whatsThis />
            <toolTip />
            <iconText />
            <activationFlags>10000</activationFlags>
            <activationConditions>0</activationConditions>
            <shortcut></shortcut>
            <isCheckable>false</isCheckable>
            <statusTip />
        </Action>
        <Action name="ai_diffusion_toggle_preview">
            <icon />
            <text>Toggle preview</text>
            <whatsThis />
            <toolTip />
            <iconText />
            <activationFlags>10000</activationFlags>
            <activationConditions>0</activationConditions>
            <shortcut></shortcut>
            <isCheckable>false</isCheckable>
            <statusTip />
        </Action>
        <Action name="ai_diffusion_apply">
            <icon />
            <text>Apply result</text>
            <whatsThis />
            <toolTip />
            <iconText />
            <activationFlags>10000</activationFlags>
            <activationConditions>0</activationConditions>
            <shortcut></shortcut>
            <isCheckable>false</isCheckable>
            <statusTip />
        </Action>
        <Action name="ai_diffusion_apply_alternative">
            <icon />
            <text>Apply result (layer)</text>
            <whatsThis />
            <toolTip />
            <iconText />
            <activationFlags>10000</activationFlags>
            <activationConditions>0</activationConditions>
            <shortcut></shortcut>
            <isCheckable>false</isCheckable>
            <statusTip />
        </Action>
        <Action name="ai_diffusion_create_region">
            <icon />
            <text>Create region</text>
            <whatsThis />
            <toolTip />
            <iconText />
            <activationFlags>10000</activationFlags>
            <activationConditions>0</activationConditions>
            <shortcut></shortcut>
            <isCheckable>false</isCheckable>
            <statusTip />
        </Action>
        <Action name="ai_diffusion_switch_workspace_generation">
            <icon />
            <text>Switch workspace: Generate</text>
            <whatsThis />
            <toolTip />
            <iconText />
            <activationFlags>10000</activationFlags>
            <activationConditions>0</activationConditions>
            <shortcut></shortcut>
            <isCheckable>false</isCheckable>
            <statusTip />
        </Action>
        <Action name="ai_diffusion_switch_workspace_upscaling">
            <icon />
            <text>Switch workspace: Upscale</text>
            <whatsThis />
            <toolTip />
            <iconText />
            <activationFlags>10000</activationFlags>
            <activationConditions>0</activationConditions>
            <shortcut></shortcut>
            <isCheckable>false</isCheckable>
            <statusTip />
        </Action>
        <Action name="ai_diffusion_switch_workspace_live">
            <icon />
            <text>Switch workspace: Live</text>
            <whatsThis />
            <toolTip />
            <iconText />
            <activationFlags>10000</activationFlags>
            <activationConditions>0</activationConditions>
            <shortcut></shortcut>
            <isCheckable>false</isCheckable>
            <statusTip />
        </Action>
        <Action name="ai_diffusion_switch_workspace_graph">
            <icon />
            <text>Switch workspace: Graph</text>
            <whatsThis />
            <toolTip />
            <iconText />
            <activationFlags>10000</activationFlags>
            <activationConditions>0</activationConditions>
            <shortcut></shortcut>
            <isCheckable>false</isCheckable>
            <statusTip />
        </Action>
        <Action name="ai_diffusion_toggle_workspace">
            <icon />
            <text>Toggle workspace</text>
            <whatsThis />
            <toolTip />
            <iconText />
            <activationFlags>10000</activationFlags>
            <activationConditions>0</activationConditions>
            <shortcut></shortcut>
            <isCheckable>false</isCheckable>
            <statusTip />
        </Action>
        <Action name="ai_diffusion_settings">
            <icon />
            <text>Show Settings</text>
            <whatsThis />
            <toolTip />
            <iconText />
            <activationFlags>0</activationFlags>
            <activationConditions>0</activationConditions>
            <shortcut></shortcut>
            <isCheckable>false</isCheckable>
            <statusTip />
        </Action>
    </Actions>
</ActionCollection>